name: Deploy

# Trigger the workflow on push and
# pull request events on the master branch
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          # host: ${{ secrets.HOST }}
          # username: ${{ secrets.USERNAME }}
          # port: ${{ secrets.PORT }}
          password : "//Indonesia//123a"
          host: 157.230.251.188
          username: "root"
          port: "22"
          script: "cd /var/www/portal_rw_021_burangkeng_react && ./deploy.sh"

          
